engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  tslint:
    enabled: true
    config: tslint.json
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
exclude_paths:
- "dist/**"
- "js/**"
- "lib/**"
